-- Run this entire file in the Supabase SQL Editor.
-- It can be run again safely when new character chapters are added.
-- Enable Anonymous Sign-Ins in Authentication settings after running it.

create table if not exists public.chapter_reactions (
  chapter_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (chapter_id, user_id)
);

create table if not exists public.chapter_comments (
  id bigint generated by default as identity primary key,
  chapter_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'Anonymous'
    check (char_length(display_name) between 1 and 80),
  body text not null
    check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

-- Remove the old fixed chapter allowlist, if it exists.
alter table public.chapter_reactions
  drop constraint if exists chapter_reactions_chapter_id_check;
alter table public.chapter_comments
  drop constraint if exists chapter_comments_chapter_id_check;

-- Use a reusable length check so future character pages work without another migration.
alter table public.chapter_reactions
  drop constraint if exists chapter_reactions_chapter_id_length_check;
alter table public.chapter_reactions
  add constraint chapter_reactions_chapter_id_length_check
  check (char_length(chapter_id) between 1 and 120);

alter table public.chapter_comments
  drop constraint if exists chapter_comments_chapter_id_length_check;
alter table public.chapter_comments
  add constraint chapter_comments_chapter_id_length_check
  check (char_length(chapter_id) between 1 and 120);

create index if not exists chapter_reactions_chapter_idx
  on public.chapter_reactions (chapter_id, reaction);

create index if not exists chapter_comments_chapter_created_idx
  on public.chapter_comments (chapter_id, created_at desc);

alter table public.chapter_reactions enable row level security;
alter table public.chapter_comments enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.chapter_reactions to authenticated;
grant select on public.chapter_reactions to anon;
grant select, insert on public.chapter_comments to authenticated;
grant select on public.chapter_comments to anon;
grant usage, select on sequence public.chapter_comments_id_seq to authenticated;

drop policy if exists "Anyone can read reactions" on public.chapter_reactions;
create policy "Anyone can read reactions"
on public.chapter_reactions for select
to anon, authenticated
using (true);

drop policy if exists "Anonymous users can add their reaction" on public.chapter_reactions;
create policy "Anonymous users can add their reaction"
on public.chapter_reactions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Anonymous users can update their reaction" on public.chapter_reactions;
create policy "Anonymous users can update their reaction"
on public.chapter_reactions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Anonymous users can remove their reaction" on public.chapter_reactions;
create policy "Anonymous users can remove their reaction"
on public.chapter_reactions for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Anyone can read comments" on public.chapter_comments;
create policy "Anyone can read comments"
on public.chapter_comments for select
to anon, authenticated
using (true);

drop policy if exists "Anonymous users can add comments" on public.chapter_comments;
create policy "Anonymous users can add comments"
on public.chapter_comments for insert
to authenticated
with check (auth.uid() = user_id);
