-- Run this entire file once in the Supabase SQL Editor.
-- Then enable Anonymous Sign-Ins in Authentication settings.

create table if not exists public.chapter_reactions (
  chapter_id text not null check (chapter_id in (
    'tiberius-kael-norek',
    'exam',
    'shareen-maxamillian',
    'lower-commodore',
    'middle-commodore',
    'randolph-5',
    'fleet-admiral',
    'victorious'
  )),
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (chapter_id, user_id)
);

create index if not exists chapter_reactions_chapter_idx
  on public.chapter_reactions (chapter_id, reaction);

create table if not exists public.chapter_comments (
  id bigint generated by default as identity primary key,
  chapter_id text not null check (chapter_id in (
    'tiberius-kael-norek',
    'exam',
    'shareen-maxamillian',
    'lower-commodore',
    'middle-commodore',
    'randolph-5',
    'fleet-admiral',
    'victorious'
  )),
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'Anonymous'
    check (char_length(display_name) between 1 and 80),
  body text not null
    check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists chapter_comments_chapter_created_idx
  on public.chapter_comments (chapter_id, created_at desc);

alter table public.chapter_reactions enable row level security;
alter table public.chapter_comments enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.chapter_reactions to authenticated;
grant select on public.chapter_reactions to anon;
grant select, insert on public.chapter_comments to authenticated;
grant select on public.chapter_comments to anon;
grant usage, select on sequence public.chapter_comments_id_seq to authenticated;

drop policy if exists "Anyone can read reactions" on public.chapter_reactions;
create policy "Anyone can read reactions"
on public.chapter_reactions for select
to anon, authenticated
using (true);

drop policy if exists "Anonymous users can add their reaction" on public.chapter_reactions;
create policy "Anonymous users can add their reaction"
on public.chapter_reactions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Anonymous users can update their reaction" on public.chapter_reactions;
create policy "Anonymous users can update their reaction"
on public.chapter_reactions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Anonymous users can remove their reaction" on public.chapter_reactions;
create policy "Anonymous users can remove their reaction"
on public.chapter_reactions for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Anyone can read comments" on public.chapter_comments;
create policy "Anyone can read comments"
on public.chapter_comments for select
to anon, authenticated
using (true);

drop policy if exists "Anonymous users can add comments" on public.chapter_comments;
create policy "Anonymous users can add comments"
on public.chapter_comments for insert
to authenticated
with check (auth.uid() = user_id);
